# Generated by Django 5.2.6 on 2025-09-20 22:00

from django.db import migrations

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX CONCURRENTLY IF NOT EXISTS album_photo_embedding_hnsw_cosine_idx
            ON album_photo
            USING hnsw (embedding vector_cosine_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS album_photo_embedding_hnsw_cosine_idx;",
        ),
    ]
