# Generated by Django 5.2.6 on 2025-10-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprocessingsettings',
            name='album_admin_processing_limit',
            field=models.IntegerField(default=50, help_text='Maximum number of photos an album admin can process in one batch (site admins have no limit)'),
        ),
    ]
