# Generated by Django 5.2.6 on 2025-10-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_add_registration_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprocessingsettings',
            name='auto_process_on_upload',
            field=models.BooleanField(default=False, help_text='[FUTURE FEATURE] Automatically process photos/videos with AI when uploaded. Currently disabled - use scheduled processing or manual processing instead.'),
        ),
    ]
