# Generated by Django 5.2.6 on 2025-10-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0009_disable_auto_process_future_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sentry_enabled',
            field=models.BooleanField(default=False, help_text='Enable Sentry error tracking. Requires SENTRY_DSN to be configured in environment variables.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sentry_profiles_sample_rate',
            field=models.FloatField(default=0.1, help_text='Sample rate for profiling (0.0 to 1.0). 0.1 = 10% of requests.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sentry_traces_sample_rate',
            field=models.FloatField(default=0.1, help_text='Sample rate for performance monitoring (0.0 to 1.0). 0.1 = 10% of requests.'),
        ),
    ]
