# Generated by Django 5.2.6 on 2025-11-09 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0010_add_sentry_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='allow_registration',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='sentry_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='sentry_profiles_sample_rate',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='sentry_traces_sample_rate',
        ),
        migrations.AlterField(
            model_name='aiprocessingsettings',
            name='auto_process_on_upload',
            field=models.BooleanField(default=True, help_text='Automatically process photos/videos with AI when uploaded'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, album is visible to all users.'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='unique_album_per_user'),
        ),
    ]
