# Generated by Django 5.2.6 on 2025-11-16 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0011_unique_album_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='album.video'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='album.photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='Upload the photo file.', max_length=255, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(help_text='Upload the video file.', max_length=255, upload_to='videos/'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('photo__isnull', False), ('video__isnull', True)), models.Q(('photo__isnull', True), ('video__isnull', False)), _connector='OR'), name='favorite_photo_or_video_not_both'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('photo__isnull', False)), fields=('user', 'photo'), name='unique_user_photo'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('video__isnull', False)), fields=('user', 'video'), name='unique_user_video'),
        ),
    ]
