# Generated by Django 5.2.6 on 2025-11-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0012_add_video_to_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_album_download_size_mb',
            field=models.PositiveIntegerField(default=2048, help_text='Maximum album download size in megabytes (MB). Default is 2048 MB (2 GB).'),
        ),
    ]
