# Generated by Django 5.2.6 on 2025-11-27 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0013_sitesettings_max_album_download_size_mb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(db_index=True, help_text='Unique token for the share link.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this share link expires.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this share link is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this link has been accessed.')),
                ('created_by', models.ForeignKey(help_text='User who created this share link.', on_delete=django.db.models.deletion.CASCADE, related_name='created_photo_share_links', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(help_text='Photo being shared.', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='album.photo')),
            ],
            options={
                'verbose_name': 'Photo Share Link',
                'verbose_name_plural': 'Photo Share Links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['share_token'], name='album_photo_share_t_9c0d73_idx'), models.Index(fields=['expires_at'], name='album_photo_expires_1a274c_idx'), models.Index(fields=['is_active'], name='album_photo_is_acti_b30bc5_idx')],
            },
        ),
    ]
