# =============================================================================
# GPU Override for Production Docker Compose
# =============================================================================
# Use this file to enable GPU support on systems with NVIDIA GPUs
# Usage: docker compose -f docker-compose.prod.yml -f docker-compose.gpu.yml up -d
# =============================================================================

services:
  web:
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  celery-worker:
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
