# Docker Compose Override for Development
# Usage: docker-compose -f docker-compose.light.yml -f docker-compose.dev.yml up -d
#
# This file mounts the code as volumes so changes are reflected immediately
# without needing to rebuild the Docker image.

version: '3.8'

services:
  web:
    volumes:
      # Mount application code for live editing
      - ./album:/app/album
      - ./photo_album:/app/photo_album
      - ./manage.py:/app/manage.py
      
      # Mount media and static (already in base, but explicit here)
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./logs:/app/logs
    
    environment:
      # Enable debug mode for development
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=photo_album.settings

  celery-worker:
    volumes:
      # Mount application code for live editing
      - ./album:/app/album
      - ./photo_album:/app/photo_album
      - ./media:/app/media
    environment:
      - DEBUG=True
