# Ruff configuration for Django Photo Album project
# https://docs.astral.sh/ruff/

# Python version target
target-version = "py313"

# Line length (Django standard is 119, PEP 8 is 88)
line-length = 119

# Directories to exclude from linting
extend-exclude = [
    "migrations",
    "staticfiles",
    "static_root",
    "media",
    "venv",
    ".venv",
    "__pycache__",
    "*.pyc",
    ".pytest_cache",
    ".coverage",
    "htmlcov",
    "build",
    "dist",
]

[lint]
# Enable specific rule sets
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # pyflakes
    "I",      # isort (import sorting)
    "N",      # pep8-naming
    "UP",     # pyupgrade (modern Python syntax)
    "B",      # flake8-bugbear (common bugs)
    "C4",     # flake8-comprehensions
    "DJ",     # flake8-django (Django-specific checks)
    "PIE",    # flake8-pie (misc lints)
    "T20",    # flake8-print (catch print statements)
    "SIM",    # flake8-simplify
    "RUF",    # Ruff-specific rules
]

# Disable specific rules
ignore = [
    "E501",   # Line too long (handled by formatter)
    "B008",   # Do not perform function calls in argument defaults (common in Django)
    "B904",   # Raise without from inside except (too strict)
    "DJ001",  # Avoid using null=True on string-based fields (valid use case)
    "T201",   # Print statement (useful for debugging)
    "SIM108", # Use ternary operator (sometimes less readable)
]

# Allow fix for all enabled rules (except specific ones)
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
# Ignore specific rules in specific files
"__init__.py" = ["F401"]  # Unused imports in __init__.py
"settings.py" = ["F405"]  # May be undefined from star imports
"**/tests/**/*.py" = [
    "S101",   # Use of assert detected (assert is ok in tests)
    "S105",   # Possible hardcoded password (test passwords are ok)
    "S106",   # Possible hardcoded password (test passwords are ok)
    "B011",   # Do not assert False (useful in tests)
]
"**/migrations/**/*.py" = ["ALL"]  # Don't lint migration files

[lint.isort]
# Configure import sorting (isort replacement)
force-single-line = false
force-sort-within-sections = false
lines-after-imports = 2
known-first-party = ["album", "photo_album"]
known-third-party = ["django"]
section-order = [
    "future",
    "standard-library", 
    "third-party",
    "first-party",
    "local-folder"
]

[lint.mccabe]
# Maximum cyclomatic complexity
max-complexity = 10

[lint.pydocstyle]
# Docstring conventions
convention = "google"

[format]
# Use double quotes for strings
quote-style = "double"

# Indent with spaces
indent-style = "space"

# Use `\n` line endings
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings
docstring-code-format = true

# Skip magic trailing comma
skip-magic-trailing-comma = false
