# Generated by Django 5.2.6 on 2025-09-20 23:17

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_add_hnsw_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ai_confidence_score',
            field=models.FloatField(default=0.0, help_text='AI prediction confidence'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ai_description',
            field=models.TextField(blank=True, help_text='AI-generated description'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='ai_processing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='ai_processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated tags'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_safe_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='nsfw_score',
            field=models.FloatField(default=0.0, help_text='NSFW detection score'),
        ),
        migrations.AddField(
            model_name='photo',
            name='perceptual_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='photo',
            name='text_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_processing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='video',
            name='is_safe_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='nsfw_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='text_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
