# Generated by Django 5.2.6 on 2025-10-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("album", "0003_photo_ai_confidence_score_photo_ai_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of AI processing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of AI processing",
                max_length=20,
            ),
        ),
    ]
