# Generated by Django 5.2.6 on 2025-10-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("album", "0004_add_processing_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProcessingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_process_on_upload",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically process photos/videos with AI when uploaded",
                    ),
                ),
                (
                    "scheduled_processing",
                    models.BooleanField(
                        default=True,
                        help_text="Enable scheduled batch processing of pending items",
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=500,
                        help_text="Maximum number of items to process per scheduled run",
                    ),
                ),
                (
                    "processing_timeout",
                    models.IntegerField(
                        default=30,
                        help_text="Timeout in seconds for processing each item",
                    ),
                ),
                (
                    "schedule_hour",
                    models.IntegerField(
                        default=2,
                        help_text="Hour of the day (0-23) to run scheduled processing",
                    ),
                ),
                (
                    "schedule_minute",
                    models.IntegerField(
                        default=0,
                        help_text="Minute of the hour (0-59) to run scheduled processing",
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Processing Settings",
                "verbose_name_plural": "AI Processing Settings",
            },
        ),
    ]
