# Generated by Django 5.2.6 on 2025-10-18 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("album", "0005_add_ai_processing_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terms_accepted",
                    models.BooleanField(
                        default=False, help_text="User has accepted Terms of Conduct"
                    ),
                ),
                (
                    "terms_accepted_date",
                    models.DateTimeField(
                        blank=True, help_text="Date when user accepted terms", null=True
                    ),
                ),
                (
                    "terms_accepted_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address when terms were accepted",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
