# Generated by Django 5.2.6 on 2025-10-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_add_album_admin_processing_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_registration',
            field=models.BooleanField(default=True, help_text='Allow new users to register. Uncheck to disable public registration.'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, album is visible to all users.', verbose_name='Is Public'),
        ),
    ]
